# Generated by Django 3.0.7 on 2020-06-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
