# Generated by Django 3.0.7 on 2020-06-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20200623_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
