# Generated by Django 3.0.7 on 2020-06-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20200623_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collection.Collection'),
        ),
    ]
