# Generated by Django 3.0.7 on 2020-07-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200701_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
